# Group Events3
Event resources

## Events [/public/events/{workflowId}/]
Get event(s) generated under a specific workflowId.

+ Parameters
    + workflowId (required, string, `8d21a912-561a-48ff-b31b-00d600a2544e`) ... `workflowId` representing a collection of related events in the form of a GUID.

+ Model (application/json)

    JSON representation of A Event.

    + Body

            [{
                "$type" : "Pbp.Contracts.Shared.Parking.Events.ParkingSessionCreated, Pbp.Contracts.Shared",
                "vehiclePlate" : "WEST111",
                "vehicleState" : "BC",
                "vehicleType" : "Car",
                "locationId" : 8990,
                "parkingSessionId" : "4f53q912-561a-48ff-b31b-00d600a2544e",
                "vendorLocationId" : "ZZ2532",
                "stall" : "",
                "startTime" : "2014-08-17T17:12:47.2834849Z",
                "expireTime" : "2014-08-17T17:42:47.2834849Z",
                "vendorId" : 504,
                "account" : "76662345678"
            },
            {
                "$type" : "Pbp.Contracts.Shared.Parking.Events.ParkingSessionExtended, Pbp.Contracts.Shared",
                "vehicleState" : "BC",
                "vehicleType" : "Car",
                "vehiclePlate" : "DFDFDF",
                "newExpiryTime" : "2014-09-17T18:42:47.2834849Z",
                "oldExpiryTime" : "2014-09-17T17:42:47.2834849Z",
                "locationId" : 8990,
                "vendorLocationId" : "RR1235",
                "stall": "",
                "vendorId" : 504,
                "account" : "76662345678",
                "extensionLvpId" : "B2982F39-0373-4486-A200-24FE7AC68F45"
            },
            {
                "$type": "Pbp.Contracts.Shared.Payments.Events.PaymentAccountCreated, Pbp.Contracts.Shared",
                "memberId": "B2982F39-0373-4486-A200-24FE7AC68F45",
                "paymentAccountId": "B2982F39-0373-4486-A200-24FE7AC68F45",
                "maskedCardNumber": "411111------1111",
                "expiryMonth": 12,
                "expiryYear": 2015,
                "nameOnCard": "John Smith",
                "issueNumber": 31,
                "startMonth": 1,
                "startYear": 2014
            },
            {
                "$type": "Pbp.Contracts.Shared.Payments.Events.ParkingQuoteAccepted, Pbp.Contracts.Shared",
                "vendorId": 504,
                "locationId": 8990,
                "accountId": "76662345678",
                "licencePlate": "ABC123",
                "startTime": "2015-10-16T19:10:14-0000",
                "expireTime": "2015-10-16T19:10:14-0000",
                "eligibilityType": "VIS",
                "parkingSessionId": "4f53q912-561a-48ff-b31b-00d600a2544e",
                "stall": "",
                "vehicleId": 452,
                "amount": {
                       "amount": 5.00,
                       "currency": "CAD"
                }
            },
            {
                "locationId": 3107,
                "stall": 0,
                "licensePlate": "TEST111",
                "parkingAccountId": "8c12d339-b0e4-49b2-838a-9ff4fa379951",
                "duration":{
                        "timeUnit":Hours",
                        "quantity":"9"
                    },
                "startTime": "2015-09-24T10:45:00Z",
                "cvv": "****",
                "$type": "Pbp.Contracts.Shared.Parking.Events.StartParkingRequested, Pbp.Contracts.Shared"
            },
            {
                 "parkingAccountId": "23fccd39-70c2-446f-915c-6d2362b64e28",
                 "vehicleId": "12793707",
                 "countryCode": "CA",
                 "licensePlate": "GGG328",
                 "jurisdiction": "MB",
                 "vehicleType": "motorcycle",
                 "$type": "Pbp.Contracts.Shared.Parking.Events.VehicleUpdated, Pbp.Contracts.Shared"
            },
            {
                 "parkingAccountId": "23fccd39-70c2-446f-915c-6d2362b64e28",
                 "vehicleId": "12793707",
                 "countryCode": "CA",
                 "licensePlate": "GGG328",
                 "jurisdiction": "MB",
                 "vehicleType": "motorcycle",
                 "$type": "Pbp.Contracts.Shared.Parking.Events.VehicleUpdatedRequested, Pbp.Contracts.Shared"
            },
            {
                 "parkingAccountId": "23fccd39-70c2-446f-915c-6d2362b64e28",
                 "countryCode": "CA",
                 "licensePlate": "GGG328",
                 "jurisdiction": "MB",
                 "vehicleType": "motorcycle",
                 "$type": "Pbp.Contracts.Shared.Parking.Events.VehicleAdded, Pbp.Contracts.Shared"
            }
            {
                 "parkingAccountId": "23fccd39-70c2-446f-915c-6d2362b64e28",
                 "countryCode": "CA",
                 "licensePlate": "GGG328",
                 "jurisdiction": "MB",
                 "vehicleType": "motorcycle",
                 "$type": "Pbp.Contracts.Shared.Parking.Events.VehicleAddRequested, Pbp.Contracts.Shared"
            },
            {
                 "ParkingSessionId": "4f53q912-561a-48ff-b31b-00d600a2544e"
                 "parkingAccountId": "23fccd39-70c2-446f-915c-6d2362b64e28",
                 "duration":{
                        "timeUnit":Hours",
                        "quantity":"9"
                 },
                 "cvv": "****",
                 "$type": "Pbp.Contracts.Shared.Parking.Events.ExtendParkingRequested, Pbp.Contracts.Shared"
            },
            {
                "$type": "Pbp.Contracts.Shared.UserAccounts.Events.UserAccountPasswordChanged, Pbp.Contracts.Shared",
                "userAccountId": "8d21a912-561a-48ff-b31b-00d600a2544e",
            }]
            
### Retrieve all parking events in a workflow [GET]

Workflow is identified by the workflowId.

**Request Contract**

    Header: Authorization: Bearer <token>
    
**Mandatory Fields**

- workflowId 

**Response Contract**

        Content-Type: application/json
        [{
            "$type" : "Pbp.Contracts.Shared.Parking.Events.ParkingSessionCreated, Pbp.Contracts.Shared",
            "vehiclePlate" : "WEST111",
            "vehicleState" : "BC",
            "vehicleType" : "Car",
            "locationId" : 8990,
            "parkingSessionId" : "4f53q912-561a-48ff-b31b-00d600a2544e",
            "vendorLocationId" : "ZZ2532",
            "stall" : "",
            "startTime" : "2014-09-17T17:12:47.2834849Z",
            "expireTime" : "2014-09-17T17:42:47.2834849Z",
            "vendorId" : 504,
            "account" : "76662345678"
        },
        {
            "$type" : "Pbp.Contracts.Shared.Parking.Events.ParkingSessionExtended, Pbp.Contracts.Shared",
            "vehicleState" : "BC",
            "vehicleType" : "Car",
            "vehiclePlate" : "DFDFDF",
            "newExpiryTime" : "2014-09-17T18:42:47.2834849Z",
            "oldExpiryTime" : "2014-09-17T17:42:47.2834849Z",
            "locationId" : 8990,
            "vendorLocationId" : "ZZ2532",
            "stall": "",
            "vendorId" : 504,
            "account" : "76662345678",
            "extensionLvpId" : "B2982F39-0373-4486-A200-24FE7AC68F45"
        },
        {
            "$type": "Pbp.Contracts.Shared.Payments.Events.PaymentAccountCreated, Pbp.Contracts.Shared",
            "memberId": "B2982F39-0373-4486-A200-24FE7AC68F45",
            "paymentAccountId": "B2982F39-0373-4486-A200-24FE7AC68F45",
            "maskedCardNumber": "411111------1111",
            "expiryMonth": 12,
            "expiryYear": 2015,
            "nameOnCard": "John Smith",
            "issueNumber": 31,
            "startMonth": 1,
            "startYear": 2014
        },
        {
            "$type": "Pbp.Contracts.Shared.Payments.Events.ParkingQuoteAccepted, Pbp.Contracts.Shared",
            "vendorId": 504,
            "locationId": 8990,
            "accountId": "76662345678",
            "licencePlate": "ABC123",
            "startTime": "2015-10-16T19:10:14-0000",
            "expireTime": "2015-10-16T19:10:14-0000",
            "eligibilityType": "VIS",
            "parkingSessionId": "4f53q912-561a-48ff-b31b-00d600a2544e",
            "stall": "",
            "vehicleId": 452,
            "amount": {
                   "amount": 5.00,
                   "currency": "CAD"
            }
        },
        {
            "locationId": 3107,
            "stall": 0,
            "licensePlate": "TEST111",
            "parkingAccountId": "8c12d339-b0e4-49b2-838a-9ff4fa379951",
            "duration":{
                    "timeUnit":Hours",
                    "quantity":"9"
                },
            "startTime": "2015-09-24T10:45:00Z",
            "cvv": "****",
            "$type": "Pbp.Contracts.Shared.Parking.Events.StartParkingRequested, Pbp.Contracts.Shared"
        },
        {
             "parkingAccountId": "23fccd39-70c2-446f-915c-6d2362b64e28",
             "vehicleId": "12793707",
             "countryCode": "CA",
             "licensePlate": "GGG328",
             "jurisdiction": "MB",
             "vehicleType": "motorcycle",
             "$type": "Pbp.Contracts.Shared.Parking.Events.VehicleUpdated, Pbp.Contracts.Shared"
        },
         {
             "parkingAccountId": "23fccd39-70c2-446f-915c-6d2362b64e28",
             "vehicleId": "12793707",
             "countryCode": "CA",
             "licensePlate": "GGG328",
             "jurisdiction": "MB",
             "vehicleType": "motorcycle",
             "$type": "Pbp.Contracts.Shared.Parking.Events.VehicleUpdatedRequested, Pbp.Contracts.Shared"
        },
        {
             "parkingAccountId": "23fccd39-70c2-446f-915c-6d2362b64e28",
             "countryCode": "CA",
             "licensePlate": "GGG328",
             "jurisdiction": "MB",
             "vehicleType": "motorcycle",
             "$type": "Pbp.Contracts.Shared.Parking.Events.VehicleAdded, Pbp.Contracts.Shared"
        },
        {
             "parkingAccountId": "23fccd39-70c2-446f-915c-6d2362b64e28",
             "countryCode": "CA",
             "licensePlate": "GGG328",
             "jurisdiction": "MB",
             "vehicleType": "motorcycle",
             "$type": "Pbp.Contracts.Shared.Parking.Events.VehicleAddRequested, Pbp.Contracts.Shared"
        },
        {
             "ParkingSessionId": "4f53q912-561a-48ff-b31b-00d600a2544e"
             "parkingAccountId": "23fccd39-70c2-446f-915c-6d2362b64e28",
             "duration":{
                    "timeUnit":Hours",
                    "quantity":"9"
             },
             "cvv": "****",
             "$type": "Pbp.Contracts.Shared.Parking.Events.ExtendParkingRequested, Pbp.Contracts.Shared"
        },
        {
            "$type": "Pbp.Contracts.Shared.UserAccounts.Events.UserAccountPasswordChanged, Pbp.Contracts.Shared",
            "userAccountId": "8d21a912-561a-48ff-b31b-00d600a2544e",
        }]

**Possible Response Codes**

- 200
- 400
- 401
- 500

+ Request all fields supplied
    
        All mandatory fields supplied
+ Response 200
    [Events][]

+ Response 500
    
        Unhandled error

+ Request missing workflowId field

        Missing {workflowId}
+ Response 400

        {"error": "The request is invalid"}

+ Request missing or invalid authorization

        Authoriazation header field is missing or bearer token is not valid
+ Response 401

        {"message":"Authorization has been denied for this request."}