# Group FeedItems
FeedItem resources

## Feeditems [/public/notifications/feedItems?since={since}&limit={limit}]
Get item(s) from the member activity feed starting from a specific UTC date and time, returned in reverse chronological order.

+ Parameters
    + since (required, string, `2014-06-10T08:56:04.0000Z`) ... Start UTC date and time from which to retrieve the activity feed items
    + limit (required, number, `50`) ... The maximum number of items to retrieve from the activity feed

+ Model (application/json)

    JSON representation of A Feeditem.

    + Body

            [{
                "subject": "SFMTA Advisory",
                "content": "Please be aware that MUNI will be closed for service upgrades on Wednesday nights from 3:00 am to 4:00 am.",
                "timeStampRfc3339": "2014-07-08T15:42:12Z",
                "imageUrlPath": "https://si0.twimg.com/profile_images/3288835160/696dc7d131ccb873b1c399dcb08d0c8c.jpeg",
                "moreDetailsUrl": "http://www.sfmta.com", 
                "type": "Service Update"
            },
            {
                "subject": "Parking Complete",
                "content": "Parking For:  \r\nLocation: 20506621 \r\nExpired: 03/07/2014 12:37 PM \r\nCost: $0.54\r\n",
                "timeStampRfc3339": "2014-07-03T12:38:35Z",
                "imageUrlPath": "http://paybyphone.co.uk/images/app_assets/pbp_icon.png",
                "moreDetailsUrl": "http://www.google.com",
                "type": "Parking History"
            }]
            
### Retrieve all feed items for a member [GET]

Member is identified by the userAccountId extracted from the access token.

**Request Contract**

    Header: Authorization: Bearer <token>
    
**Mandatory Fields**

- since
- limit

**Response Contract**

        Content-Type: application/json
        [{
                "subject": "",
                "content": "",
                "timeStampRfc3339": "",
                "imageUrlPath": "",
                "moreDetailsUrl": "", 
                "type": ""
        },
        {
                "subject": "",
                "content": "",
                "timeStampRfc3339": "",
                "imageUrlPath": "",
                "moreDetailsUrl": "", 
                "type": ""                
        }]

**Possible Response Codes**

- 200
- 400
- 401
- 500

+ Request all fields supplied
    
        All mandatory fields supplied
+ Response 200
    [Feeditems][]

+ Response 500
    
        Unhandled error

+ Response 400

        {"error": "The request is invalid"}

+ Request missing since field

        Missing {since}
+ Response 400

        {"error": "The request is invalid"}

+ Request missing limit field

        Missing {limit}
+ Response 400

        {"error": "The request is invalid"}

+ Request missing or invalid authorization

        Authoriazation header field is missing or bearer token is not valid
+ Response 401

        {"message":"Authorization has been denied for this request."}