This is a list of PayByPhone Apis

## Response Codes
The common [HTTP Response Status Codes](http://tools.ietf.org/html/rfc7231#section-6) are used.

## Error Handling

Any code you write to call PayByPhone's APIs should expect to receive and handle errors from the service. A given error may be returned for multiple reasons, so it's a good idea to look at (and handle in code), the error messages returned with the error number.

400-series errors indicate that you cannot perform the requested action, the most common reasons being that you don't have permission or that a referred-to entity doesn't exist.

500-series errors indicate that a request didn't succeed, but may be retried. Though infrequent, these errors are to be expected as part of normal interaction with the service and should be explicitly handled with an exponential backoff algorithm. One such algorithm can be found at http://en.wikipedia.org/wiki/Truncated_binary_exponential_backoff.

Failed connection attempts should also be handled with exponential backoff.

# Data Structures

## Money (object)
+ amount: `5.00` (number)
+ currencyCodeISO4217: `CAD` (string)


## QuoteItem (object)
+ quoteItemType: `parking` (string) - XXXXXXXX
+ name: `Parking` (string) - XXXXXXXX
+ costAmout (Money)


## GetParkingQuoteResponse (object)
+ locationNumber: `40002` (string) - XXXXXXXX
+ stallId: `123` (string) - XXXXXXXX
+ quoteDate: `2015-06-25T18:00:00-0000` (string) - XXXXXXXX
+ totalCost: (Money) - XXXXXXXX
+ parkingAccountId: `56514ff5-44fc-463b-820f-1d47393e1703` (string) - XXXXXXXX
+ parkingStartTime: `2014-12-29T22:00:00-0000` (string) - XXXXXXXX
+ parkingExpiryTime: `2014-12-29T23:00:00-0000` (string) - XXXXXXXX
+ parkingDurationAdjustment: (enum) - XXXXXXXX
    + NotAdjusted (string) - XXXXXXXX
    + DurationIncreased (string) - XXXXXXXX
    + DurationDecreased (string) - XXXXXXXX
    + DurationIncreasedPromptUserToConfirm (string) - XXXXXXXX
+ licensePlate: `ABC123` (string) - XXXXXXXX
+ quoteItems: (array) - XXXXXXXX
    + (QuoteItem)


## PaymentAccount (object)
+ id: `+16046155905` (string) - E.164 phone number used to create user account.
+ maskedCardNumber: `411111------1111` (string) - Assigned by the API at the moment of creation.
+ paymentCardType: `DebitCard` (string) - Assigned by the API at the moment of creation.
+ nameOnCard: `JOHN L SMITH` (string) - Assigned by the API at the moment of creation.
+ expiryMonth: `2` (number) - Assigned by the API at the moment of creation.
+ expiryYear: `2018` (number) - Assigned by the API at the moment of creation.
+ startMonth: `2` (number) - Assigned by the API at the moment of creation.
+ startYear: `2012` (number) - Assigned by the API at the moment of creation.
+ issueNumber: `2` (number) - Assigned by the API at the moment of creation.


## PaymentAccounts (array)
+ (PaymentAccount) - An array of PaymentAccount objects


## CreatePaymentAccount (object)
+ countryCode (enum, required) - Country the card is registered in.
    + CA (string)
    + US (string)
    + AU (string)
    + FR (string)
    + CH (string)
    + GB (string)
+ cardNumber: `4111111111111111` (string, required) - The credit or debit card number.
+ expiryMonth: `2` (number, required) - Expiration month of the card.
+ expiryYear: `2018` (number, required) - Expiration year of the card.
+ nameOnCard: `JOHN L SMITH` (string) - The card holders name as it appears on the card.
+ cvv : `123` (string) - The Card Verification Value
+ issueNumber: `2` (number) - The issue number for the debit card.
+ startMonth: `2` (number) - Assigned by the API at the moment of creation.
+ startYear: `2012` (number) - Assigned by the API at the moment of creation.