# Group Parking Quote
Parking  resources

## Quote [/public/parking/quote?location={location}&timeUnit={timeUnit}&quantity={quantity}]
A quote based on submitted input parameters

+ Parameters
    + location (required, number) ... Numeric `location` to park
    + timeUnit (required, string) ... timeunit for parking
    + quantity (required, number) ... timeunit quantity for parking

+ Model (application/json)

    JSON representation of A Quote.

    + Body

            {
                "locationNumber": "10202990",
                "stallId": null,
                "quoteDate": "2014-07-22T10:14:40-0000",
                "totalCost": {
                  "amount": 2.35,
                  "currencyCodeISO4217": "USD"
                },
                "parkingStartTime":"2014-07-22T10:14:40-0000",
                "parkingExpiryTime":"2014-07-22T11:14:40-0000"
            }

### Retrieve quote [GET]
**Request Contract**

    Header: Authorization: Bearer <token>

**Response Contract**
    
    Content-Type: application/json
    {
        "locationNumber": "10202990",
        "stallId": null,
        "quoteDate": "2014-07-22T10:14:40-0000",
        "totalCost": {
          "amount": 2.35,
          "currencyCodeISO4217": "USD"
        },
        "parkingStartTime":"2014-07-22T10:14:40-0000",
        "parkingExpiryTime":"2014-07-22T11:14:40-0000"
    }

+ Response 200
    [Quote][]

+ Response 400

        {
            "error": 
            "The request is invalid"
        }