# Group Payment Accounts

## Payment Accounts [/public/payment/accounts]

The Payment Accounts root resource

+ Model (application/json)

    JSON representation of Payment Account

    + Body

            { 
                "id": "72de36abf64447d3944bacae39ea1f7d",
                "paymentCardType": "Visa",
                "nameOnCard": "JOHN L SMITH",
                "expiryMonth": 1,
                "expiryYear": 2019,
                "startMonth": null,
                "startYear": null,
                "issueNumber": null
            }

### Create a new payment account for a member [POST]

The Member is identified by the **memberid** claim in the authorization bearer token

**Request Contract**

    Header: Authorization: Bearer <token>
    Content-Type: application/json
    {
        "cardNumber": "4111111111111111",
        "expiryMonth": 1,
        "expiryYear": 2019,
        "countryCode": "CA",
        "nameOnCard": "JOHN L SMITH",
        "cvv": 123,
        "issueNumber": 12,
        "startYear": 2010,
        "startMonth": 1
    }

**Mandatory Fields**

- countryCode (string : [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2))
- number (string : [Bank card number](http://en.wikipedia.org/wiki/Bank_card_number))
- expiryYear (integer : >= current year - current year + 10)
- expiryMonth (integer : 1-12, > current month if current year)

**Mandatory Fields for North America**

- name (string)

**Mandatory Fields for France**

- cvv (integer : 3-4 digits)

**Optional Fields for United Kingdom**

- startMonth (integer : 1-12, <= current month if current year)
- startYear (integer : <= current year)
- issueNumber (integer : 2 digits)

**Possible Validation Errors**

- StartMonthMustBeLessOrEqualToCurrentMonthWhenStartYearIsCurrentYear StartMonthOutOfRange
- StartYearMustBeLessOrEqualToCurrentYear
- StartMonthIsRequiredWhenStartYearIsProvided
- IssueNumberMustBeDigits
- IssueNumberMustBe1Or2Digits
- StartYearMustBeEmpty
- StartMonthMustBeEmpty
- IssueNumberMustBeEmpty
- CvvMustNotBeEmpty
- CvvMustBeDigits
- CvvMustBeEmpty
- NameOnCardMustNotBeEmpty
- NameOnCardInvalidFormat
- NameOnCardMustBeBetween2And70Characters
- NameOnCardMustBeEmpty
- ExpiryMonthMustNotBeEmpty
- ExpiryMonthMustBeAValidMonthNumber
- ExpiryMonthMustBeGreaterThanOrEqualToCurrentMonth
- ExpiryYearMustNotBeEmpty
- ExpiryYearMustBeLessThanOrEqualToCurrentYearPlus10
- ExpiryYearMustBeGreaterThanOrEqualToCurrentYear
- CardNumberInvalidFormat
- CardNumberFailedLuhnTest
- UnknownCardType
- CountryMustNotBeEmpty
- CountryUnknown
- YouCanNotCreateSecondPaymentMethodWithSameCcNumber

**Possible events**

- PaymentAccountCreated_V3
       
        {
            "paymentAccountId": "549cd539-07df-450b-8abc-3a73b99ab338",
            "memberId": "4c9cd539-a9e2-4769-be8d-ced9e0e15a89",
            "maskedCardNumber": "496379------6452",
            "expiryMonth": 12,
            "expiryYear": 2020,
            "nameOnCard": "John Smith",
            "issueNumber": null,
            "startMonth": null,
            "startYear": null,
            "$type": "PaymentAccountCreated_V3"
        }

- CreatePaymentAccountFailed_V3

        {
            "Data": [ ],
            "FailureReason":"YouCanNotCreateSecondPaymentMethodWithSameCcNumber",
            "$type":"CreatePaymentAccountFailed_V3"
        }
        
**Possible Response Codes**

- 202 - Accepted
- 400 - Bad Request
- 401 - Unauthorized

+ Request NA with name (application/json)

        {
            "cardNumber": "4111111111111111",
            "countryCode": "CA",            
            "expiryMonth": 6,
            "expiryYear": 2016,
            "nameOnCard": "JOHN L SMITH"
        }
+ Response 202 (application/json)
    + Header

            Location: http://api.dev.paybyphone.com/public/events/8d21a912-561a-48ff-b31b-00d600a2544e/

+ Request NA no name (application/json)

        {
            "cardNumber": "4111111111111111",
            "countryCode": "CA",            
            "expiryMonth": 6,
            "expiryYear": 2016
        }
+ Response 202 (application/json)
    + Header

            Location: http://api.dev.paybyphone.com/public/events/8d21a912-561a-48ff-b31b-00d600a2544e/

+ Request UK start mm/yy (application/json)

        {
            "cardNumber": "4111111111111111",
            "countryCode": "UK",
            "expiryMonth": 6,
            "expiryYear": 2016,
            "startMonth": 1,
            "startYear": 2012
        }
+ Response 202 (application/json)
    + Header

            Location: http://api.dev.paybyphone.com/public/events/8d21a912-561a-48ff-b31b-00d600a2544e/

+ Request UK issuenumber (application/json)

        {
            "cardNumber": "4111111111111111",
            "countryCode": "UK",            
            "expiryMonth": 6,
            "expiryYear": 2016,
            "issueNumber": 12
        }
+ Response 202 (application/json)
    + Header

            Location: http://api.dev.paybyphone.com/public/events/8d21a912-561a-48ff-b31b-00d600a2544e/
        
+ Request FR (application/json)

        {
            "cardNumber": "4111111111111111",
            "countryCode": "FR",            
            "expiryMonth": 6,
            "expiryYear": 2016,
            "cvv": 111
        }
+ Response 202 (application/json)
    + Header

            Location: http://api.dev.paybyphone.com/public/events/8d21a912-561a-48ff-b31b-00d600a2544e/

+ Response 401 (application/json)

        {"error": "Unauthorized"}

+ Response 500 (application/json)

        {"error": "Unhandled error"}
        
### Retrieve all payment accounts for member [GET]

Retrieve all Payment Accounts for a Member.

The Member is identified by the **memberid** claim in the authorization bearer token

**Request Contract**

    Header: Authorization: Bearer <token>

**Response Contract**
    
    Content-Type: application/json
    [
         {
            "id": "81c8d439-aa44-4338-8b76-cc920bf50225",
            "maskedCardNumber": "411111------1111",
            "paymentCardType": "Visa",
            "nameOnCard": "John Smith",
            "expiryMonth": 12,
            "expiryYear": 2018,
            "startMonth": null,
            "startYear": null,
            "issueNumber": null
        },
        {
            "id": "81c8d439-aa44-4338-8b76-cc920bf50225",
            "maskedCardNumber": "49637-------6452",
            "paymentCardType": "Visa",
            "nameOnCard": "Test12151420",
            "expiryMonth": 12,
            "expiryYear": 2019,
            "startMonth": null,
            "startYear": null,
            "issueNumber": null
        }
    ]
    
**Possible Response Codes**

- 200 - OK
- 401 - Unauthorized

+ Request
    
        /public/payment/accounts
+ Response 200
        [Payment Accounts][]

+ Response 401 (application/json)

        {"error": "Unauthorized"}

+ Response 500 (application/json)

        {"error": "Unhandled error"}

## Payment Account [/public/payment/accounts/{paymentAccountId}]

An individual Payment Account resource

+ Parameters
    + paymentAccountId (required, guid) ... Guid `paymentAccountId` of the User Resource to perform action with. Has example value.

+ Model (application/json)

    JSON representation of Payment Account

    + Body

            { 
                "id": "72de36abf64447d3944bacae39ea1f7d",
                "paymentCardType": "Visa",
                "nameOnCard": "Test",
                "expiryMonth": 1,
                "expiryYear": 2019,
                "startMonth": null,
                "startYear": null,
                "issueNumber": null
            }
            
### Retrieve a payment account for member [GET]

Retrieve a Payment Account for a Member.

The Member is identified by the **memberid** claim in the authorization bearer token

Payment Account is identified by the `paymentAccountId`

**Request Contract**

    Header: Authorization: Bearer <token>

**Response Contract**
    
    Content-Type: application/json
    {
        "id": "81c8d439-aa44-4338-8b76-cc920bf50225",
        "maskedCardNumber": "411111------1111",
        "paymentCardType": "Visa",
        "nameOnCard": "Test",
        "expiryMonth": 12,
        "expiryYear": 2014,
        "startMonth": null,
        "startYear": null,
        "issueNumber": null
    }
    
**Possible Response Codes**

- 200 - OK
- 400 - Bad Request
- 401 - Unauthorized

+ Request paymentAccountId exists
    
        /public/payment/accounts/{paymentAccountId}
+ Response 200
        [Payment Account][]

+ Request paymentAccountId Does Not exists
        
        /public/payment/accounts/{paymentAccountId}
+ Response 404 (application/json)

        {"error": "Not found"}

+ Request paymentAccountId is not a Guid
        
        /public/payment/accounts/{paymentAccountId}
+ Response 400 (application/json)

        {"error": "PaymentAccountIdInvalidFormat"}

+ Response 401 (application/json)

        {"error": "Unauthorized"}

+ Response 500 (application/json)

        {"error": "Unhandled error"}


### Delete a payment account for a member [DELETE]

Delete a Payment Account for a Member.

The Member is identified by the **memberid** claim in the authorization bearer token

Payment Account is identified by the `paymentAccountId`.

**Request Contract**

    Header: Authorization: Bearer <token>

**Possible Failure reasons**

- PaymentAccountDoesntBelongToMember
- DataError

**Possible events**

- PaymentAccountDeleted_V3
       
        {
            "memberId": "4c9cd539-a9e2-4769-be8d-ced9e0e15a89",
            "paymentAccountId": "549cd539-07df-450b-8abc-3a73b99ab338",
            "$type":"PaymentAccountDeleted_V3"
        }

- DeletePaymentAccountFailed_V3

        {
            "Data": [ ],
            "FailureReason":"PaymentAccountDoesntBelongToMember",
            "$type":"DeletePaymentAccountFailed_V3"
        }

**Possible Response Codes**

- 202 - Accepted
- 400 - Bad Request
- 401 - Unauthorized
- 403 - Forbidden

+ Request paymentAccountId Exists

        /public/payment/accounts/{paymentAccountId}
+ Response 202 (application/json)
    + Header

            Location: http://api.dev.paybyphone.com/public/events/8d21a912-561a-48ff-b31b-00d600a2544e/

+ Request paymentAccountId Does Not Exists

        /public/payment/accounts/{paymentAccountId}
+ Response 202 (application/json)
    + Header

            Location: http://api.dev.paybyphone.com/public/events/8d21a912-561a-48ff-b31b-00d600a2544e/

+ Response 401 (application/json)

        {"error": "Unauthorized"}

+ Response 500 (application/json)

        {"error": "Unhandled error"}